repos:
  # Hooks for basic whitespace fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace  # Remove trailing whitespace
      - id: end-of-file-fixer  # Ensure files end with a newline
      - id: check-yaml  # Validate YAML files

  # Hook for enforcing Black formatting
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Use the latest stable version of Black
    hooks:
      - id: black
        language_version: python3  # Use Python 3 for formatting
